name: Thai

on:
  push:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Cache requirements
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config.json"
          json: ${{ secrets.CONFIG }}
      - name: Test with behave
        run: |
          REST_PASSWORD=${{ secrets.REST_PASSWORD }}
          GERMANY_REST_URL=${{ secrets.GERMANY_REST_URL }}
          CAPTCHA_API_KEY=${{ secrets.CAPTCHA_API_KEY }}
          python3 visa_thai/thai.py
